---
title: "Sales Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

# Core Libraries
library(tidyverse)
library(tidyquant)
library(lubridate)

# Interactive Viz
library(plotly)

# Database
library(odbc)
library(RSQLite)
```

```{r}
con <- dbConnect(RSQLite::SQLite(), "../00_data/bikes_database.db")
#dbListTables(con)
bikes_tbl <- tbl(con,"bikes")
bikeshops_tbl <- tbl(con, "bikeshops")
orderlines_tbl <- tbl(con, "orderlines")

processed_data_tbl <- orderlines_tbl %>%
    left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id")) %>%
    left_join(bikes_tbl, by = c("product.id"="bike.id")) %>%
    mutate(extended_price = quantity * price) %>%
    collect() %>%
    
    # Do this after collect()
    separate(col = location, into = c("cit","state"), sep = ", ") %>%
    mutate(order.date = ymd(order.date)) %>%
    select(order.date, order.id, order.line, state, quantity, price, extended_price)

#processed_data_tbl

dbDisconnect(conn = con)
```

## Column {data-width=1000}

### By State